---
openapi: 3.0.3
info:
  title: Department API (development)
  description: Department service
  termsOfService: Your terms here
  contact:
    name: Department API Support
    url: http://exampleurl.com/contact
    email: techsupport@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /api/v1/hr/employee/{employeeId}/assign/department/{deptId}:
    post:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                format: int32
                type: integer
  /api/v1/hr/employee/{employeeId}/unassign:
    delete:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                format: int32
                type: integer
